name: build
on:
  push:
    branches:
    - main
    - feature/gha-build
  workflow_dispatch:

env:
  NETSDKVERSION: '6.0.x'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      NetSdkVersion: ${{ steps.setVars.outputs.netSdkVersion }}
    steps:
    - id: setVars
      run: |
        echo "netSdkVersion=$NETSDKVERSION" >> $GITHUB_OUTPUT
      env:
        NETSDKVERSION: ${{ env.NETSDKVERSION }}

  build:
    needs:
    - setup
    uses: ./.github/workflows/endjin-scripted-build.yml
    with:
      netSdkVersion: ${{ needs.setup.NetSdkVersion }}
      tasks: 'Build,Analysis'

  test:
    needs:
    - setup
    - build
    uses: ./.github/workflows/endjin-scripted-build.yml
    with:
      netSdkVersion: ${{ needs.setup.NetSdkVersion }}
      tasks: 'Test,TestReport'