name: build
on:
  push:
    branches:
    - main
    - feature/gha-build
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    needs:
    - setup
    uses: endjin/Endjin.RecommendedPractices.GitHubActions/.github/workflows/scripted-build-pipeline.yml@main
    with:
      netSdkVersion: '6.0.x'