name: build
on:
  push:
    branches:
    - main
    - feature/gha-build
  workflow_dispatch:
    inputs:
      forcePublish:
        description: When true the Publish stage will always be run, otherwise it only runs for tagged versions.
        required: false
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: endjin/Endjin.RecommendedPractices.GitHubActions/.github/workflows/scripted-build-pipeline.yml@main
    with:
      netSdkVersion: '6.0.x'
      forcePublish: ${{ github.event.inputs.forcePublish }}