name: build
on:
  push:
    branches:
    - main
    - feature/gha-build
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/endjin-scripted-build.yml
    with:
      netSdkVersion: '6.0.x'
      tasks: 'Build,Analysis'
