name: build
on:
  push:
    branches:
    - main
    - feature/gha-build
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NETSDKVERSION: '6.0.x'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      NetSdkVersion: ${{ steps.setVars.outputs.netSdkVersion }}
    steps:
    - id: setVars
      run: |
        echo "netSdkVersion=$NETSDKVERSION" >> $GITHUB_OUTPUT
      env:
        NETSDKVERSION: ${{ env.NETSDKVERSION }}

  build:
    needs:
    - setup
    uses: ./.github/workflows/endjin-scripted-build.yml
    with:
      jobShortName: compile
      displayName: Compile & Analyse
      netSdkVersion: ${{ needs.setup.NetSdkVersion }}
      tasks: 'Build,Analysis'

  test:
    if: false   # disabled whilst tests are disabled in build.ps1
    needs:
    - setup
    - build
    uses: ./.github/workflows/endjin-scripted-build.yml
    with:
      jobShortName: test
      displayName: Run Tests
      netSdkVersion: ${{ needs.setup.NetSdkVersion }}
      tasks: 'Test,TestReport'

  package:
    needs:
    - setup
    - build
    uses: ./.github/workflows/endjin-scripted-build.yml
    with:
      jobShortName: package
      displayName: Build Packages
      netSdkVersion: ${{ needs.setup.NetSdkVersion }}
      tasks: 'Package'